// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvh-iJO6xCcGJ9UMypjb7BPBckAOO8_YU',
    appId: '1:465593903381:web:7258c489f8ca8eed95611c',
    messagingSenderId: '465593903381',
    projectId: 'social-93f9f',
    authDomain: 'social-93f9f.firebaseapp.com',
    storageBucket: 'social-93f9f.appspot.com',
    measurementId: 'G-BSCELTF7E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHoLw7Gsw6ABgUWYWnrJ9BysJiwkh6jZg',
    appId: '1:465593903381:android:20017d622e678b9b95611c',
    messagingSenderId: '465593903381',
    projectId: 'social-93f9f',
    storageBucket: 'social-93f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx6yxznFrP3K5Hb7baUAR5dQZxuDy9lBI',
    appId: '1:465593903381:ios:21ac35dc0278f91a95611c',
    messagingSenderId: '465593903381',
    projectId: 'social-93f9f',
    storageBucket: 'social-93f9f.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx6yxznFrP3K5Hb7baUAR5dQZxuDy9lBI',
    appId: '1:465593903381:ios:a01cb6db9a643bc295611c',
    messagingSenderId: '465593903381',
    projectId: 'social-93f9f',
    storageBucket: 'social-93f9f.appspot.com',
    iosBundleId: 'com.example.social.RunnerTests',
  );
}
